version: '3'
services:
  lugo-api:
    container_name: lugo-api
    build:
      context: .
      target: dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://lugo:passw0rd@db:5432/lugo
      - JWT_SECRET=cd0b72cdb7fd31e88e193879bde37ccdad0937b4d281a846d1aad09996cd3f6e
      - JWT_ALGORITHM=HS256
      - REDIS_URL=redis://default:passw0rd@redis:6379
      - SESSION_DURATION_SECONDS=86400
      - PORT=3000
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
  db:
    container_name: db
    image: postgres:16.1
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=lugo
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=lugo
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - REDIS_PASSWORD=passw0rd
      - REDIS_DATABASES=1
volumes:
  db-data:
